<a href="https://colab.research.google.com/github/nasrulansari133303-gif/Machine-Learning/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(f"/00 customer.csv")

In [5]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [11]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']

In [56]:
x=df[['review', 'education']]

In [57]:
y=df['purchased']
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [58]:
from sklearn.preprocessing import OrdinalEncoder

In [59]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]).set_output(transform='pandas')

In [62]:
oe.fit_transform(x)

    review  education
0      1.0        0.0
1      0.0        1.0
2      2.0        2.0
3      2.0        2.0
4      1.0        1.0
5      1.0        0.0
6      2.0        0.0
7      0.0        0.0
8      1.0        1.0
9      2.0        1.0
10     2.0        1.0
11     2.0        1.0
12     0.0        0.0
13     1.0        0.0
14     0.0        2.0
15     0.0        1.0
16     0.0        1.0
17     0.0        1.0
18     2.0        0.0
19     0.0        2.0
20     1.0        0.0
21     1.0        2.0
22     0.0        2.0
23     2.0        0.0
24     1.0        2.0
25     2.0        0.0
26     0.0        2.0
27     0.0        2.0
28     0.0        0.0
29     1.0        1.0
30     1.0        1.0
31     0.0        0.0
32     1.0        1.0
33     2.0        2.0
34     1.0        0.0
35     0.0        0.0
36     2.0        1.0
37     1.0        2.0
38     2.0        0.0
39     0.0        2.0
40     2.0        0.0
41     2.0        2.0
42     2.0        2.0
43     0.0        2.0
44     1.0        1.0
45     0.0        2.0
46     0.0        2.0
47     2.0        2.0
48     2.0        1.0
49     2.0        1.0

In [63]:
from sklearn.preprocessing import LabelEncoder

In [66]:
le=LabelEncoder()
le.fit_transform(y)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])